version: '3.8'

services:
  # dev:
  #   container_name: nestjs_api_dev
  #   image: nestjs-api-dev:1.0.0
  #   build:
  #       context: .
  #       target: development
  #       dockerfile: ./Dockerfile
  #   command: npm run start:debug
  #   ports:
  #       - 3000:3000
  #       - 9229:9229
  #   volumes:
  #       - .:/usr/src/app
  #       - /usr/src/app/node_modules
  #   restart: unless-stopped
  # prod:
  #   container_name: nestjs_api_prod
  #   image: nestjs-api-prod:1.0.0
  #   build:
  #       context: .
  #       target: production
  #       dockerfile: ./Dockerfile
  #   command: npm run start:prod
  #   ports:
  #       - 3000:3000
  #       - 9229:9229
  #   volumes:
  #       - .:/usr/src/app
  #       - /usr/src/app/node_modules
  #   restart: unless-stopped
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: myblogdb
      POSTGRES_USER: mybloguser
      POSTGRES_PASSWORD: myblogpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres-data: