version: '3'

services:
  web:
    image: node:20
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - .:/app
    command: npm run start:debug
    env_file:
      - .env
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: myblogdb
      POSTGRES_USER: mybloguser
      POSTGRES_PASSWORD: myblogpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres-data: